// AKC-recognized breeds, grouped. Source: AKC "Breeds by Year Recognized" (through 2026).
// Varieties that differ only by size/coat (Poodle, Collie, Dachshund, Chihuahua,
// Manchester Terrier) are kept as a single breed. Smooth and Wire Fox Terriers are
// listed separately, as the AKC recognizes them as distinct breeds.
const BREEDS = [
  // ---- Sporting ----
  { n: "American Water Spaniel", g: "Sporting" },
  { n: "Barbet", g: "Sporting" },
  { n: "Boykin Spaniel", g: "Sporting" },
  { n: "Bracco Italiano", g: "Sporting" },
  { n: "Brittany", g: "Sporting" },
  { n: "Chesapeake Bay Retriever", g: "Sporting" },
  { n: "Clumber Spaniel", g: "Sporting" },
  { n: "Cocker Spaniel", g: "Sporting" },
  { n: "Curly-Coated Retriever", g: "Sporting" },
  { n: "English Cocker Spaniel", g: "Sporting" },
  { n: "English Setter", g: "Sporting" },
  { n: "English Springer Spaniel", g: "Sporting" },
  { n: "Field Spaniel", g: "Sporting" },
  { n: "Flat-Coated Retriever", g: "Sporting" },
  { n: "German Shorthaired Pointer", g: "Sporting" },
  { n: "German Wirehaired Pointer", g: "Sporting" },
  { n: "Golden Retriever", g: "Sporting" },
  { n: "Gordon Setter", g: "Sporting" },
  { n: "Irish Red and White Setter", g: "Sporting" },
  { n: "Irish Setter", g: "Sporting" },
  { n: "Irish Water Spaniel", g: "Sporting" },
  { n: "Labrador Retriever", g: "Sporting" },
  { n: "Lagotto Romagnolo", g: "Sporting" },
  { n: "Nederlandse Kooikerhondje", g: "Sporting" },
  { n: "Nova Scotia Duck Tolling Retriever", g: "Sporting" },
  { n: "Pointer", g: "Sporting" },
  { n: "Spinone Italiano", g: "Sporting" },
  { n: "Sussex Spaniel", g: "Sporting" },
  { n: "Vizsla", g: "Sporting" },
  { n: "Weimaraner", g: "Sporting" },
  { n: "Welsh Springer Spaniel", g: "Sporting" },
  { n: "Wirehaired Pointing Griffon", g: "Sporting" },
  { n: "Wirehaired Vizsla", g: "Sporting" },

  // ---- Hound ----
  { n: "Afghan Hound", g: "Hound" },
  { n: "American English Coonhound", g: "Hound" },
  { n: "American Foxhound", g: "Hound" },
  { n: "Azawakh", g: "Hound" },
  { n: "Basenji", g: "Hound" },
  { n: "Basset Fauve de Bretagne", g: "Hound" },
  { n: "Basset Hound", g: "Hound" },
  { n: "Beagle", g: "Hound" },
  { n: "Black and Tan Coonhound", g: "Hound" },
  { n: "Bloodhound", g: "Hound" },
  { n: "Bluetick Coonhound", g: "Hound" },
  { n: "Borzoi", g: "Hound" },
  { n: "Cirneco dell'Etna", g: "Hound" },
  { n: "Dachshund", g: "Hound" },
  { n: "English Foxhound", g: "Hound" },
  { n: "Grand Basset Griffon Vendéen", g: "Hound" },
  { n: "Greyhound", g: "Hound" },
  { n: "Harrier", g: "Hound" },
  { n: "Ibizan Hound", g: "Hound" },
  { n: "Irish Wolfhound", g: "Hound" },
  { n: "Norwegian Elkhound", g: "Hound" },
  { n: "Otterhound", g: "Hound" },
  { n: "Petit Basset Griffon Vendéen", g: "Hound" },
  { n: "Pharaoh Hound", g: "Hound" },
  { n: "Plott Hound", g: "Hound" },
  { n: "Portuguese Podengo Pequeno", g: "Hound" },
  { n: "Redbone Coonhound", g: "Hound" },
  { n: "Rhodesian Ridgeback", g: "Hound" },
  { n: "Saluki", g: "Hound" },
  { n: "Scottish Deerhound", g: "Hound" },
  { n: "Sloughi", g: "Hound" },
  { n: "Treeing Walker Coonhound", g: "Hound" },
  { n: "Whippet", g: "Hound" },

  // ---- Working ----
  { n: "Akita", g: "Working" },
  { n: "Alaskan Malamute", g: "Working" },
  { n: "Anatolian Shepherd Dog", g: "Working" },
  { n: "Bernese Mountain Dog", g: "Working" },
  { n: "Black Russian Terrier", g: "Working" },
  { n: "Boerboel", g: "Working" },
  { n: "Boxer", g: "Working" },
  { n: "Bullmastiff", g: "Working" },
  { n: "Cane Corso", g: "Working" },
  { n: "Chinook", g: "Working" },
  { n: "Doberman Pinscher", g: "Working" },
  { n: "Dogo Argentino", g: "Working" },
  { n: "Dogue de Bordeaux", g: "Working" },
  { n: "German Pinscher", g: "Working" },
  { n: "Giant Schnauzer", g: "Working" },
  { n: "Great Dane", g: "Working" },
  { n: "Great Pyrenees", g: "Working" },
  { n: "Greater Swiss Mountain Dog", g: "Working" },
  { n: "Komondor", g: "Working" },
  { n: "Kuvasz", g: "Working" },
  { n: "Leonberger", g: "Working" },
  { n: "Mastiff", g: "Working" },
  { n: "Neapolitan Mastiff", g: "Working" },
  { n: "Newfoundland", g: "Working" },
  { n: "Portuguese Water Dog", g: "Working" },
  { n: "Rottweiler", g: "Working" },
  { n: "Saint Bernard", g: "Working" },
  { n: "Samoyed", g: "Working" },
  { n: "Siberian Husky", g: "Working" },
  { n: "Standard Schnauzer", g: "Working" },
  { n: "Tibetan Mastiff", g: "Working" },

  // ---- Terrier ----
  { n: "Airedale Terrier", g: "Terrier" },
  { n: "American Hairless Terrier", g: "Terrier" },
  { n: "American Staffordshire Terrier", g: "Terrier" },
  { n: "Australian Terrier", g: "Terrier" },
  { n: "Bedlington Terrier", g: "Terrier" },
  { n: "Border Terrier", g: "Terrier" },
  { n: "Bull Terrier", g: "Terrier" },
  { n: "Cairn Terrier", g: "Terrier" },
  { n: "Cesky Terrier", g: "Terrier" },
  { n: "Dandie Dinmont Terrier", g: "Terrier" },
  { n: "Glen of Imaal Terrier", g: "Terrier" },
  { n: "Irish Terrier", g: "Terrier" },
  { n: "Kerry Blue Terrier", g: "Terrier" },
  { n: "Lakeland Terrier", g: "Terrier" },
  { n: "Manchester Terrier", g: "Terrier" },
  { n: "Miniature Bull Terrier", g: "Terrier" },
  { n: "Miniature Schnauzer", g: "Terrier" },
  { n: "Norfolk Terrier", g: "Terrier" },
  { n: "Norwich Terrier", g: "Terrier" },
  { n: "Parson Russell Terrier", g: "Terrier" },
  { n: "Rat Terrier", g: "Terrier" },
  { n: "Russell Terrier", g: "Terrier" },
  { n: "Scottish Terrier", g: "Terrier" },
  { n: "Sealyham Terrier", g: "Terrier" },
  { n: "Skye Terrier", g: "Terrier" },
  { n: "Smooth Fox Terrier", g: "Terrier" },
  { n: "Soft Coated Wheaten Terrier", g: "Terrier" },
  { n: "Staffordshire Bull Terrier", g: "Terrier" },
  { n: "Teddy Roosevelt Terrier", g: "Terrier" },
  { n: "Welsh Terrier", g: "Terrier" },
  { n: "West Highland White Terrier", g: "Terrier" },
  { n: "Wire Fox Terrier", g: "Terrier" },

  // ---- Toy ----
  { n: "Affenpinscher", g: "Toy" },
  { n: "Biewer Terrier", g: "Toy" },
  { n: "Brussels Griffon", g: "Toy" },
  { n: "Cavalier King Charles Spaniel", g: "Toy" },
  { n: "Chihuahua", g: "Toy" },
  { n: "Chinese Crested", g: "Toy" },
  { n: "English Toy Spaniel", g: "Toy" },
  { n: "Havanese", g: "Toy" },
  { n: "Italian Greyhound", g: "Toy" },
  { n: "Japanese Chin", g: "Toy" },
  { n: "Maltese", g: "Toy" },
  { n: "Miniature Pinscher", g: "Toy" },
  { n: "Papillon", g: "Toy" },
  { n: "Pekingese", g: "Toy" },
  { n: "Pomeranian", g: "Toy" },
  { n: "Pug", g: "Toy" },
  { n: "Russian Toy", g: "Toy" },
  { n: "Russian Tsvetnaya Bolonka", g: "Toy" },
  { n: "Shih Tzu", g: "Toy" },
  { n: "Silky Terrier", g: "Toy" },
  { n: "Toy Fox Terrier", g: "Toy" },
  { n: "Yorkshire Terrier", g: "Toy" },

  // ---- Non-Sporting ----
  { n: "American Eskimo Dog", g: "Non-Sporting" },
  { n: "Bichon Frise", g: "Non-Sporting" },
  { n: "Boston Terrier", g: "Non-Sporting" },
  { n: "Bulldog", g: "Non-Sporting" },
  { n: "Chinese Shar-Pei", g: "Non-Sporting" },
  { n: "Chow Chow", g: "Non-Sporting" },
  { n: "Coton de Tulear", g: "Non-Sporting" },
  { n: "Dalmatian", g: "Non-Sporting" },
  { n: "Finnish Spitz", g: "Non-Sporting" },
  { n: "French Bulldog", g: "Non-Sporting" },
  { n: "Keeshond", g: "Non-Sporting" },
  { n: "Lhasa Apso", g: "Non-Sporting" },
  { n: "Löwchen", g: "Non-Sporting" },
  { n: "Norwegian Lundehund", g: "Non-Sporting" },
  { n: "Poodle", g: "Non-Sporting" },
  { n: "Schipperke", g: "Non-Sporting" },
  { n: "Shiba Inu", g: "Non-Sporting" },
  { n: "Tibetan Spaniel", g: "Non-Sporting" },
  { n: "Tibetan Terrier", g: "Non-Sporting" },
  { n: "Xoloitzcuintli", g: "Non-Sporting" },

  // ---- Herding ----
  { n: "Australian Cattle Dog", g: "Herding" },
  { n: "Australian Shepherd", g: "Herding" },
  { n: "Bearded Collie", g: "Herding" },
  { n: "Beauceron", g: "Herding" },
  { n: "Belgian Laekenois", g: "Herding" },
  { n: "Belgian Malinois", g: "Herding" },
  { n: "Belgian Sheepdog", g: "Herding" },
  { n: "Belgian Tervuren", g: "Herding" },
  { n: "Bergamasco Sheepdog", g: "Herding" },
  { n: "Berger Picard", g: "Herding" },
  { n: "Border Collie", g: "Herding" },
  { n: "Bouvier des Flandres", g: "Herding" },
  { n: "Briard", g: "Herding" },
  { n: "Canaan Dog", g: "Herding" },
  { n: "Cardigan Welsh Corgi", g: "Herding" },
  { n: "Collie", g: "Herding" },
  { n: "Danish-Swedish Farmdog", g: "Herding" },
  { n: "Entlebucher Mountain Dog", g: "Herding" },
  { n: "Finnish Lapphund", g: "Herding" },
  { n: "German Shepherd Dog", g: "Herding" },
  { n: "Icelandic Sheepdog", g: "Herding" },
  { n: "Lancashire Heeler", g: "Herding" },
  { n: "Miniature American Shepherd", g: "Herding" },
  { n: "Mudi", g: "Herding" },
  { n: "Norwegian Buhund", g: "Herding" },
  { n: "Old English Sheepdog", g: "Herding" },
  { n: "Pembroke Welsh Corgi", g: "Herding" },
  { n: "Polish Lowland Sheepdog", g: "Herding" },
  { n: "Puli", g: "Herding" },
  { n: "Pumi", g: "Herding" },
  { n: "Pyrenean Shepherd", g: "Herding" },
  { n: "Shetland Sheepdog", g: "Herding" },
  { n: "Spanish Water Dog", g: "Herding" },
  { n: "Swedish Vallhund", g: "Herding" }
];

const GROUPS = ["Sporting", "Hound", "Working", "Terrier", "Toy", "Non-Sporting", "Herding"];

function breedSlug(name) {
  return name
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")   // Löwchen -> Lowchen
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
